### ISSUE TITLE
Request to Add a "Stop Stream" Command

### ISSUE THREAD

**Issue by dbian** [MatissJurevics/Gene-AI#2]
Hello,

As an enthusiastic user of this plugin, I have noticed that it currently lacks a convenient way to stop the streaming functionality when interacting with OpenAI's API.

Having a designated command to stop the stream would allow users to have better control over the assistant's responses and enable more efficient interactions. This command could be implemented as a simple text command or a keyboard shortcut within the plugin's interface.

Please let me know if there is any further information or assistance I can provide to support the implementation of this feature.

Best regards.

**Comment by MatissJurevics** [comment]
Hi,

Thats a great idea! I'll start looking into how I can implement it now and ill update you on my progress and if theres any assistance I may need.

Thank you for your interest in Gene,
Matiss Jurevics

**Comment by MatissJurevics** [comment]
I've released a stop stream command in version 1.3.4. I'm going to leave this issue open so if you find any bugs or issues with the stop stream command please leave them here.
